server:
  port: 7010
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaozhikang157/springCloudConfig
          username:
          password:
          search-paths:
      label: master

