server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaozhikang157/springCloudConfig
          username:
          password:
          search-paths: respo
      label: master